name: Tourism Project Pipeline

on:
  push:
    branches:
    - main  # Automatically triggers on push to the main branch

jobs:

  data-prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tourism_project/requirements.txt
      - name: Run Data Preparation
        run: |
          python -m tourism_project.model_building.prep
      - name: Upload Data Splits
        uses: actions/upload-artifact@v4
        with:
          name: data-splits
          path: |
            Xtrain.csv
            Xtest.csv
            ytrain.csv
            ytest.csv

  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Data Splits
        uses: actions/download-artifact@v4
        with:
          name: data-splits
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tourism_project/requirements.txt
      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &
          sleep 5
      - name: Model Building
        run: |
          python -m tourism_project.model_building.train
